#!/usr/bin/env bash
# scan_all.sh — run /scan across crates in parallel Claude Code sessions (Phase WF.0).
# Generated by `aetherd init-agent`; regenerate with --force after upgrading AETHER.
#
# Usage: scripts/scan_all.sh [BATCH_SIZE=100] [MAX_PARALLEL=4] [crate ...]
#
# With no arguments every workspace package from `cargo metadata` is scanned; in a
# workspace without Cargo (TypeScript, Python, ...) every top-level directory that holds
# indexed symbols is scanned instead. Arguments may be package names or directories
# relative to the workspace root. Preflight checks the index and the project-scoped
# AETHER MCP registration (.mcp.json, written by `aetherd init-agent`) that the Claude
# sessions need for `aether_sir_inject`, then counts [MOCK] / low-confidence SIRs in the
# selected scopes before and after. A running aetherd is left alone: the MCP server
# falls back to the SQLite graph when the daemon holds the SurrealKV lock. Runs on
# Bash 3.2 (stock macOS) and later.
set -euo pipefail

# Leading numeric arguments are BATCH_SIZE then MAX_PARALLEL; everything else is a crate
# name, so `scripts/scan_all.sh aether-core` and `scripts/scan_all.sh 50 aether-core` both work.
BATCH_SIZE=100
MAX_PARALLEL=4
if [ "$#" -gt 0 ] && [[ "$1" =~ ^[0-9]+$ ]]; then
  BATCH_SIZE="$1"; shift
  if [ "$#" -gt 0 ] && [[ "$1" =~ ^[0-9]+$ ]]; then
    MAX_PARALLEL="$1"; shift
  fi
fi
if [ "$BATCH_SIZE" -lt 1 ] || [ "$MAX_PARALLEL" -lt 1 ]; then
  echo "error: BATCH_SIZE and MAX_PARALLEL must be positive integers (got $BATCH_SIZE, $MAX_PARALLEL)" >&2
  exit 1
fi

# The workspace is the directory this script was generated into (its parent), not the
# Git root: an AETHER workspace may sit inside a larger repository.
WORKSPACE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$WORKSPACE"
DB=".aether/meta.sqlite"
LOG_DIR=".aether/scan_logs"
STAMP="$(date +%Y%m%d_%H%M%S)"
MASTER_LOG="$LOG_DIR/scan_${STAMP}.log"
mkdir -p "$LOG_DIR"

log() { printf '%s %s\n' "$(date +%H:%M:%S)" "$*" | tee -a "$MASTER_LOG"; }

if [ ! -f "$DB" ]; then
  echo "error: $DB not found. Index first with:" >&2
  echo "  aetherd --workspace . --index-once --full --inference-provider mock" >&2
  exit 1
fi
if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "error: sqlite3 is required to count scan targets" >&2
  exit 1
fi
if ! command -v claude >/dev/null 2>&1; then
  echo "error: the claude CLI is required (each scope runs as: claude -p \"/scan <crate> $BATCH_SIZE\" --allowedTools \"mcp__aether*\")" >&2
  exit 1
fi
# The sessions are non-interactive, so the AETHER MCP server must already be registered
# for this project: `.mcp.json` with an "aether" entry (the stdio aether-mcp binary,
# which opens the store itself; no daemon is required).
if [ ! -f .mcp.json ] || ! grep -q '"aether"' .mcp.json; then
  echo "error: no project-scoped AETHER MCP registration (.mcp.json with an \"aether\" server)." >&2
  echo "  Register it with: aetherd --workspace . init-agent --platform claude" >&2
  echo "  or: claude mcp add --transport stdio --scope project aether -- aether-mcp --workspace ." >&2
  exit 1
fi

# Top-level directories (or root-level files) that hold indexed symbols, straight from
# the index: the units of a project without Cargo, and the extra units of a mixed project
# (TypeScript/Python sources beside Rust packages).
index_top_level_scopes() {
  sqlite3 "$DB" "SELECT DISTINCT CASE WHEN instr(file_path, '/') > 0 THEN substr(file_path, 1, instr(file_path, '/') - 1) ELSE file_path END FROM symbols ORDER BY 1;" | awk 'NF'
}

# Prints "name<TAB>scope[<TAB>scope...]" per scan unit, scopes relative to the workspace
# root; a scope prefixed with "-" is an exclusion (a nested member's directory carved out
# of its parent's scope, so no two units overlap). A target declared outside its package
# directory brings that directory in when this package is the only one targeting it (so
# sibling modules such as `mod util;` → shared/util.rs are covered); when several
# packages target the same external directory each gets only its target file plus its
# `<stem>/` module directory, and the directory's remainder becomes its own unit.
# An indexed top-level directory whose name collides with a package is emitted as
# `dir:<name>`; explicit arguments may use that form too. Cargo workspaces: one unit per package, parsed structurally from the metadata
# JSON (packages[].name / manifest_path / targets; never the dependency or target names
# that also carry a "name" key). A package owns its manifest directory (unless that is
# the workspace root) plus, for every target whose src_path lies outside that directory,
# the directory holding the target file (the workspace root itself contributes the file
# only); so a root package owns just src/, tests/, benches/, ... or a root-level
# `path = "lib.rs"`, never the whole workspace, and `[lib] path = "../../shared/foo.rs"`
# brings shared/ in. When cargo metadata cannot be loaded, or without Cargo (or
# python3), one unit per top-level directory (or root-level file) that holds indexed
# symbols, straight from the index.
discover_packages() {
  local table="" index_tops
  index_tops="$(index_top_level_scopes)"
  if command -v cargo >/dev/null 2>&1 && [ -f Cargo.toml ] && command -v python3 >/dev/null 2>&1; then
    table="$(cargo metadata --no-deps --format-version 1 2>/dev/null | AETHER_WORKSPACE="$WORKSPACE" AETHER_INDEX_TOPS="$index_tops" python3 -c '
import json, os, sys
meta = json.load(sys.stdin)
# Scopes are relative to the AETHER workspace (where the index lives), which may be a
# single package inside a larger Cargo workspace; packages outside it are ignored.
root = os.path.realpath(os.environ["AETHER_WORKSPACE"])
def inside(path):
    rel = os.path.relpath(os.path.realpath(path), root)
    return None if rel == ".." or rel.startswith(".." + os.sep) else rel
def covered(scope, scopes):
    return any(scope == s or scope.startswith(s + os.sep) for s in scopes)
# Which packages declare targets in each external directory (outside their manifest dir).
external_owners = {}
for pkg in meta["packages"]:
    rel = inside(os.path.dirname(pkg["manifest_path"]))
    if rel is None or rel == ".":
        continue
    for target in pkg.get("targets", []):
        src = inside(target["src_path"])
        if src is None or src == rel or src.startswith(rel + os.sep):
            continue
        external_owners.setdefault(os.path.dirname(src) or ".", set()).add(pkg["name"])
units = []
for pkg in meta["packages"]:
    manifest_dir = os.path.dirname(pkg["manifest_path"])
    rel = inside(manifest_dir)
    if rel is None:
        continue
    scopes = [] if rel == "." else [rel]
    for target in pkg.get("targets", []):
        src = inside(target["src_path"])
        if src is None:
            continue
        if rel == ".":
            candidates = [src.split(os.sep)[0]]
        elif src == rel or src.startswith(rel + os.sep):
            continue
        else:
            ext_dir = os.path.dirname(src) or "."
            if ext_dir != "." and external_owners.get(ext_dir) == {pkg["name"]}:
                candidates = [ext_dir]
            else:
                candidates = [src, os.path.splitext(src)[0]]
        for scope in candidates:
            if scope and scope != "." and not covered(scope, scopes):
                scopes = [s for s in scopes if not (s == scope or s.startswith(scope + os.sep))]
                scopes.append(scope)
    if scopes:
        units.append((pkg["name"], scopes))
# A member nested below another member (crates/parent, crates/parent/child) is carved
# out of the parent so the two units never scan the same symbols.
for name, scopes in units:
    excluded = []
    for other_name, other_scopes in units:
        if other_name == name:
            continue
        for other in other_scopes:
            if any(other != s and other.startswith(s + os.sep) for s in scopes) and other not in excluded:
                excluded.append(other)
    print(name + "\t" + "\t".join(scopes + ["-" + e for e in excluded]))
# Mixed project: an indexed top-level directory (or root-level file) that no package owns
# becomes its own unit; one that merely contains packages becomes a unit minus them, so
# TypeScript/Python sources beside the Rust packages are scanned too.
package_scopes = [s for _, scopes in units for s in scopes]
unit_names = {name for name, _ in units}
for top in os.environ.get("AETHER_INDEX_TOPS", "").split("\n"):
    top = top.strip()
    if not top:
        continue
    if any(top == s or top.startswith(s + os.sep) for s in package_scopes):
        continue
    carved = [s for s in package_scopes if s.startswith(top + os.sep)]
    name = "dir:" + top if top in unit_names else top
    print(name + "\t" + "\t".join([top] + ["-" + s for s in carved]))
' 2>/dev/null || true)"
  fi
  if [ -n "$table" ]; then
    printf '%s\n' "$table"
  else
    printf '%s\n' "$index_tops" | awk 'NF { printf "%s\t%s\n", $0, $0 }'
  fi
}

# One "name<TAB>scopes" line per package (no associative arrays: Bash 3.2 lacks them).
PACKAGE_TABLE="$(discover_packages)"

# Explicit names are package names or project-relative paths; normalize the common
# spellings (`./src`, `src/`) to the form the index stores. `.` is not a unit: run with no
# arguments to scan everything.
normalize_unit() {
  local u="$1" prefix=""
  if [ "${u#dir:}" != "$u" ]; then prefix="dir:"; u="${u#dir:}"; fi
  while [ "${u#./}" != "$u" ]; do u="${u#./}"; done
  u="${u%/}"
  [ -n "$u" ] && [ "$u" != "." ] && printf '%s%s' "$prefix" "$u"
}
CRATES=()
if [ "$#" -gt 0 ]; then
  for name in "$@"; do
    unit="$(normalize_unit "$name")"
    if [ -z "$unit" ]; then
      echo "error: '$name' is not a scan unit; run scripts/scan_all.sh with no names to scan everything" >&2
      exit 1
    fi
    CRATES+=("$unit")
  done
else
  while IFS= read -r name; do
    [ -n "$name" ] && CRATES+=("$name")
  done < <(printf '%s\n' "$PACKAGE_TABLE" | cut -f1 | sort)
  if [ "${#CRATES[@]}" -eq 0 ]; then
    echo "error: nothing to scan: no Cargo packages and no indexed symbols in $DB" >&2
    exit 1
  fi
fi

# Tab-separated scopes (directories or root-level target files) for one unit. `dir:<path>`
# always means that path; other names that are not discovered units are taken as paths
# relative to the workspace root when they exist, else as crates/<name>.
crate_scopes() {
  local found
  found="$(printf '%s\n' "$PACKAGE_TABLE" | awk -F '\t' -v crate="$1" '$1 == crate { sub(/^[^\t]*\t/, ""); print; exit }')"
  if [ -n "$found" ]; then
    printf '%s' "$found"
  elif [ "${1#dir:}" != "$1" ]; then
    printf '%s' "${1#dir:}"
  elif [ -e "$1" ]; then
    printf '%s' "${1%/}"
  else
    printf 'crates/%s' "$1"
  fi
}
crate_scopes_display() { crate_scopes "$1" | tr '\t' ','; }

# SQL string literal: single quotes doubled.
sql_str() { printf '%s' "${1//\'/\'\'}"; }
# LIKE pattern for "everything under <dir>/": `\`, `%` and `_` in the path are escaped so
# they match literally (ESCAPE '\'), then the SQL quoting is applied.
sql_prefix_pattern() {
  local p="$1"
  p="${p//\\/\\\\}"; p="${p//%/\\%}"; p="${p//_/\\_}"
  sql_str "$p/%"
}
# One SQL predicate for a scope: the path itself (a root-level file) or anything below it
# (a directory), decided by the index rather than by what exists on disk right now.
scope_predicate() {
  printf "(s.file_path = '%s' OR s.file_path LIKE '%s' ESCAPE '\\\\')" "$(sql_str "$1")" "$(sql_prefix_pattern "$1")"
}
# SQL scope for the given units: only symbols under their own directories (or equal to
# a root-level target file), minus any nested member carved out with a "-" scope.
scope_clause() {
  local units=() crate scope scopes includes excludes
  for crate in "$@"; do
    includes=(); excludes=()
    IFS=$'\t' read -ra scopes <<< "$(crate_scopes "$crate")"
    for scope in "${scopes[@]}"; do
      [ -z "$scope" ] && continue
      case "$scope" in
        -*) excludes+=("$(scope_predicate "${scope#-}")") ;;
        *) includes+=("$(scope_predicate "$scope")") ;;
      esac
    done
    [ "${#includes[@]}" -eq 0 ] && continue
    local IFS=' '
    local unit="($(printf '%s OR ' "${includes[@]}" | sed 's/ OR $//'))"
    if [ "${#excludes[@]}" -gt 0 ]; then
      unit="($unit AND NOT ($(printf '%s OR ' "${excludes[@]}" | sed 's/ OR $//')))"
    fi
    units+=("$unit")
  done
  if [ "${#units[@]}" -eq 0 ]; then
    echo "error: no source directories resolved for: $*" >&2
    exit 1
  fi
  local IFS=' '
  printf '(%s)' "$(printf '%s OR ' "${units[@]}" | sed 's/ OR $//')"
}
SCOPE="$(scope_clause "${CRATES[@]}")"

# Number of [MOCK] / low-confidence SIRs inside a scope clause (default: all selected units).
count_targets() {
  local scope="${1:-$SCOPE}"
  sqlite3 "$DB" "SELECT COUNT(*) FROM sir JOIN symbols s ON s.id = sir.id WHERE $scope AND (sir.sir_json LIKE '%\"intent\":\"[MOCK]%' OR json_extract(sir.sir_json, '\$.confidence') < 0.2);"
}

NEXT_STEP="deepen the results with: aetherd --workspace . regenerate --deep --below-confidence 0.85 (or /refactor-deep on the files that matter most)"

BEFORE="$(count_targets)"
log "scan targets before: $BEFORE ([MOCK] or confidence < 0.2 in: ${CRATES[*]})"
if [ "$BEFORE" = "0" ]; then
  log "nothing to scan in the selected crates; $NEXT_STEP"
  exit 0
fi

log "scanning ${#CRATES[@]} crate(s), batch size $BATCH_SIZE, up to $MAX_PARALLEL parallel sessions"
# Bash 3.2 cannot wait for "any one job": poll the running job count instead. Failed
# sessions leave a marker so the exit status reflects them after the final wait.
running_jobs() { jobs -rp | wc -l | tr -d ' '; }
FAIL_DIR="$LOG_DIR/failed_${STAMP}"
mkdir -p "$FAIL_DIR"
for crate in "${CRATES[@]}"; do
  if [ "$(count_targets "$(scope_clause "$crate")")" = "0" ]; then
    log "skip $crate ($(crate_scopes_display "$crate")): no scan targets"
    continue
  fi
  safe_name="$(printf '%s' "$crate" | tr '/' '_')"
  crate_log="$LOG_DIR/${safe_name}_${STAMP}.log"
  log "start $crate ($(crate_scopes_display "$crate")) -> $crate_log"
  ( if claude -p "/scan $crate $BATCH_SIZE" --allowedTools "mcp__aether*" > "$crate_log" 2>&1; then
      echo "done $crate"
    else
      touch "$FAIL_DIR/$safe_name"
      echo "FAILED $crate (see $crate_log)"
    fi ) | tee -a "$MASTER_LOG" &
  while [ "$(running_jobs)" -ge "$MAX_PARALLEL" ]; do
    sleep 2
  done
done
wait
FAILED="$(ls "$FAIL_DIR" | wc -l | tr -d ' ')"
rm -rf "$FAIL_DIR"

AFTER="$(count_targets)"
log "scan targets after: $AFTER (was $BEFORE)"
log "complete: $((BEFORE - AFTER)) symbol(s) scanned; logs in $LOG_DIR"
if [ "$FAILED" != "0" ]; then
  log "error: $FAILED scan session(s) failed; see the FAILED lines above"
  exit 1
fi
if [ "$AFTER" = "$BEFORE" ]; then
  log "error: no placeholder was replaced; the sessions could not use aether_sir_inject (check $LOG_DIR for tool denials or MCP failures)"
  exit 1
fi
if [ "$AFTER" != "0" ]; then
  log "rerun scripts/scan_all.sh to continue, then $NEXT_STEP"
else
  log "$NEXT_STEP"
fi
