#!/usr/bin/env bash
# scan_all.sh — run /scan across crates in parallel Claude Code sessions (Phase WF.0).
# Generated by `aetherd init-agent`; regenerate with --force after upgrading AETHER.
#
# Usage: scripts/scan_all.sh [BATCH_SIZE=100] [MAX_PARALLEL=4] [crate ...]
#
# With no crate arguments every workspace package from `cargo metadata` is scanned
# (falling back to the directories under crates/). Preflight stops the aetherd /
# aether-mcp processes that belong to THIS workspace (the graph store holds an
# exclusive lock), checks the index exists, and counts [MOCK] / low-confidence SIRs
# in the selected crates before and after.
set -euo pipefail

# Leading numeric arguments are BATCH_SIZE then MAX_PARALLEL; everything else is a crate
# name, so `scripts/scan_all.sh aether-core` and `scripts/scan_all.sh 50 aether-core` both work.
BATCH_SIZE=100
MAX_PARALLEL=4
if [ "$#" -gt 0 ] && [[ "$1" =~ ^[0-9]+$ ]]; then
  BATCH_SIZE="$1"; shift
  if [ "$#" -gt 0 ] && [[ "$1" =~ ^[0-9]+$ ]]; then
    MAX_PARALLEL="$1"; shift
  fi
fi
if [ "$BATCH_SIZE" -lt 1 ] || [ "$MAX_PARALLEL" -lt 1 ]; then
  echo "error: BATCH_SIZE and MAX_PARALLEL must be positive integers (got $BATCH_SIZE, $MAX_PARALLEL)" >&2
  exit 1
fi

WORKSPACE="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$WORKSPACE"
DB=".aether/meta.sqlite"
LOG_DIR=".aether/scan_logs"
STAMP="$(date +%Y%m%d_%H%M%S)"
MASTER_LOG="$LOG_DIR/scan_${STAMP}.log"
mkdir -p "$LOG_DIR"

log() { printf '%s %s\n' "$(date +%H:%M:%S)" "$*" | tee -a "$MASTER_LOG"; }

# Prints "name<TAB>dir[<TAB>dir...]" per workspace package, dirs relative to the workspace
# root. Parses the metadata JSON structurally (packages[].name / manifest_path / targets);
# never the dependency or target names that also carry a "name" key. A package whose
# manifest sits at the workspace root owns only the top-level directories of its own
# targets (src/, tests/, benches/, ...), never the whole workspace.
discover_packages() {
  if command -v cargo >/dev/null 2>&1 && [ -f Cargo.toml ] && command -v python3 >/dev/null 2>&1; then
    cargo metadata --no-deps --format-version 1 2>/dev/null | python3 -c '
import json, os, sys
meta = json.load(sys.stdin)
root = os.path.realpath(meta["workspace_root"])
for pkg in meta["packages"]:
    manifest_dir = os.path.dirname(os.path.realpath(pkg["manifest_path"]))
    rel = os.path.relpath(manifest_dir, root)
    if rel != ".":
        dirs = [rel]
    else:
        dirs = []
        for target in pkg.get("targets", []):
            src = os.path.relpath(os.path.realpath(target["src_path"]), root)
            top = src.split(os.sep)[0]
            if top and top != "." and not top.startswith("..") and top not in dirs and os.sep in src:
                dirs.append(top)
    if dirs:
        print(pkg["name"] + "\t" + "\t".join(dirs))
'
  elif [ -d crates ]; then
    for dir in crates/*/; do
      name="$(basename "$dir")"
      printf '%s\t%s\n' "$name" "crates/$name"
    done
  fi
}

declare -A CRATE_DIRS=()
while IFS=$'\t' read -r name dirs; do
  [ -n "$name" ] && CRATE_DIRS["$name"]="$dirs"
done < <(discover_packages)

if [ "$#" -gt 0 ]; then
  CRATES=("$@")
else
  mapfile -t CRATES < <(printf '%s\n' "${!CRATE_DIRS[@]}" | sort)
  if [ "${#CRATES[@]}" -eq 0 ]; then
    echo "error: no crates discovered (no Cargo workspace or crates/ directory); pass crate names explicitly" >&2
    exit 1
  fi
fi

# Tab-separated directory prefixes per selected crate; unknown names fall back to crates/<name>.
crate_dirs() {
  if [ -n "${CRATE_DIRS[$1]+x}" ]; then printf '%s' "${CRATE_DIRS[$1]}"; else printf 'crates/%s' "$1"; fi
}
crate_dirs_display() { crate_dirs "$1" | tr '\t' ','; }

# Stop only the aetherd / aether-mcp processes that belong to this workspace: by cwd on
# Linux (/proc), otherwise by a --workspace argument naming this path.
stop_workspace_processes() {
  local pid cwd
  for pid in $(pgrep -f 'aetherd|aether-mcp' 2>/dev/null || true); do
    [ "$pid" = "$$" ] && continue
    cwd="$(readlink "/proc/$pid/cwd" 2>/dev/null || true)"
    if [ "$cwd" = "$WORKSPACE" ] || tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null | grep -qF -- "$WORKSPACE"; then
      kill "$pid" 2>/dev/null || true
    fi
  done
}
stop_workspace_processes

if [ ! -f "$DB" ]; then
  echo "error: $DB not found. Index first with:" >&2
  echo "  aetherd --workspace . --index-once --full --inference-provider mock" >&2
  exit 1
fi
if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "error: sqlite3 is required to count scan targets" >&2
  exit 1
fi
if ! command -v claude >/dev/null 2>&1; then
  echo "error: the claude CLI is required (each crate runs as: claude -p \"/scan <crate> $BATCH_SIZE\")" >&2
  exit 1
fi

# SQL scope: only symbols under the selected crates' own directories.
scope_clause() {
  local clauses=() crate dir dirs
  for crate in "${CRATES[@]}"; do
    IFS=$'\t' read -ra dirs <<< "$(crate_dirs "$crate")"
    for dir in "${dirs[@]}"; do
      [ -n "$dir" ] && clauses+=("s.file_path LIKE '${dir//\'/\'\'}/%'")
    done
  done
  if [ "${#clauses[@]}" -eq 0 ]; then
    echo "error: no source directories resolved for: ${CRATES[*]}" >&2
    exit 1
  fi
  local IFS=' '
  printf '(%s)' "$(printf '%s OR ' "${clauses[@]}" | sed 's/ OR $//')"
}
SCOPE="$(scope_clause)"

count_targets() {
  sqlite3 "$DB" "SELECT COUNT(*) FROM sir JOIN symbols s ON s.id = sir.id WHERE $SCOPE AND (sir.sir_json LIKE '%\"intent\":\"[MOCK]%' OR json_extract(sir.sir_json, '\$.confidence') < 0.2);"
}

NEXT_STEP="deepen the results with: aetherd --workspace . regenerate --deep --below-confidence 0.85 (or /refactor-deep on the files that matter most)"

BEFORE="$(count_targets)"
log "scan targets before: $BEFORE ([MOCK] or confidence < 0.2 in: ${CRATES[*]})"
if [ "$BEFORE" = "0" ]; then
  log "nothing to scan in the selected crates; $NEXT_STEP"
  exit 0
fi

log "scanning ${#CRATES[@]} crate(s), batch size $BATCH_SIZE, up to $MAX_PARALLEL parallel sessions"
running=0
for crate in "${CRATES[@]}"; do
  crate_log="$LOG_DIR/${crate}_${STAMP}.log"
  log "start $crate ($(crate_dirs_display "$crate")) -> $crate_log"
  ( claude -p "/scan $crate $BATCH_SIZE" > "$crate_log" 2>&1 \
      && echo "done $crate" || echo "FAILED $crate (see $crate_log)" ) | tee -a "$MASTER_LOG" &
  running=$((running + 1))
  if [ "$running" -ge "$MAX_PARALLEL" ]; then
    wait -n
    running=$((running - 1))
  fi
done
wait

AFTER="$(count_targets)"
log "scan targets after: $AFTER (was $BEFORE)"
log "complete: $((BEFORE - AFTER)) symbol(s) scanned; logs in $LOG_DIR"
if [ "$AFTER" != "0" ]; then
  log "rerun scripts/scan_all.sh to continue, then $NEXT_STEP"
else
  log "$NEXT_STEP"
fi
